# Generated by Django 3.0.5 on 2020-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_blogpost_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='picture',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
